spring:
  application:
    name: websocket${service-suffix}
    desc: DevOps Websocket Service
    version: 4.0.0
    packageName: com.tencent.devops.websocket

server:
  port: 21940

thread:
  min: 8
