# 服务配置文件模板
spring:
  application:
    name: task
    desc: Task Service
  data:
    mongodb:
      uri: mongodb://__MONGODB_USER__:__MONGODB_PASS__@__MONGODB_IP__:__MONGODB_PORT__/db_task?replicaSet=rs0&slaveOk=true

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 23910
server:
  port: __CODECC_TASK_PORT__ # 服务端口


time:
  analysis:
    maxhour: __CODECC_ANALYSIS_MAXHOUR__

devops:
  imageName: __DEVOPS_DISPATCH_DOCER_DEFAULT_IMAGE_NAME__
  retry:
    attempt: __CODECC_RETRY_ATTEMPT__
    interval: __CODECC_RETRY_INTERVAL__
