# 服务配置文件模板
spring:
  application:
    name: job
    desc: Job Service
  data:
    mongodb:
      uri: mongodb://__MONGODB_USER__:__MONGODB_PASS__@__MONGODB_IP__:__MONGODB_PORT__/db_defect?replicaSet=rs0&slaveOk=true

server:
  port: __CODECC_JOB_PORT__