# 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://__MYSQL_IP0__:__MYSQL_PORT__/devops_ci_dispatch?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: __MYSQL_USER__
    password: __MYSQL_PASS__

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21922
server:
  port: __BKCI_DISPATCH_API_PORT__

dispatch:
  workerFile: __INSTALL_PATH__/__MODULE__/agent-package/jar/worker-agent.jar
  dockerFile: __INSTALL_PATH__/__MODULE__/agent-package/jar/worker-agent.jar
  scripts: __INSTALL_PATH__/__MODULE__/agent-package/script
  defaultImageUrl: __DOCKER_IMAGE_PREFIX__:__DOCKER_PORT__/paas/bkdevops/centos7.2:v1
  defaultImageName: centos7.2
  dockerhostPort: __BKCI_DOCKERHOST_API_PORT__

codecc:
  path: __INSTALL_PATH__/public/codecc/tools
  covFile: build_dev.py
  toolFile: build_tool_dev.py