# Common config Template 重复的通用的配置抽离在到

spring:
  application:
    version: 4.0.0
  # consul config do not need to change
  redis:
    host: __REDIS_IP__
    port: __REDIS_PORT__
    password: __REDIS_PASS__
    pool:
      maxActive: 16
      maxWait: 2000
      maxIdle: 16
      minIdle: 0
  rabbitmq:
    virtual-host: __RABBITMQ_CODECC_VHOST__
    username: __RABBITMQ_USERNAME__
    password: __RABBITMQ_PASSWORD__
    addresses: __RABBITMQ_HOST__:__RABBITMQ_PORT__
  cloud:
    consul:
      discovery:
        tags: __DEVOPS_CONSUL_TAG__
        health-check-path: /management/health
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
      port: __DEVOPS_CONSUL_PORT__
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# http concurrency
server:
  servlet-path: /
  undertow:
    worker-threads: 100

# monitor path config
management:
  security:
    enabled: false
  context-path: /management


auth:
  envName: prod
  url: __CODECC_AUTH_URL__
  codeccCode: __APP_CODE__
  codeccSecret: __APP_TOKEN__
  systemId: __CODECC_SYSTEM_ID__
  resourceType: __CODECC_RESOURCE_TYPE__

devopsGateway:
  host: __DEVOPS_GATEWAY_HOST__:__DEVOPS_GATEWAY_PORT__

codeccGateway:
  host: __CODECC_GATEWAY_HOST__:__CODECC_GATEWAY_PORT__
  api: __CODECC_GATEWAY_HOST__:__CODECC_GATEWAY_PORT__



