# Image Service Template 服务配置文件模板
spring:
  datasource:
    url: jdbc:mysql://__MYSQL_IP0__:__MYSQL_PORT__/devops_ci_image?useSSL=false&autoReconnect=true&timezone=+800&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: __MYSQL_USER__
    password: __MYSQL_PASS__

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21933
server:
  port: __BKCI_IMAGE_API_PORT__


image:
  dockerCli:
    dockerHost: unix:///var/run/docker.sock
    dockerConfig: /root/.docker
    apiVersion: 1.23
    registryUrl: __JFROG_URL__
    registryUsername: __DOCKER_REGISTRY_USERNAME__
    registryPassword: __DOCKER_REGISTRY_PASSWORD__
    imagePrefix: __DOCKER_IMAGE_PREFIX__:__DOCKER_PORT__
