spring:
  cloud:
    consul:
      discovery:
        register: false
        enabled: false

# 服务器端口配置，在同一台机器上部署多个微服务，端口号要不同 21923
server:
  port: __BKCI_DOCKERHOST_API_PORT__

run:
  mode: docker_build

# docker client 配置
dockerCli:
  dockerHost: unix:///var/run/docker.sock
  dockerConfig: /root/.docker
  apiVersion: 1.23
  # docker hub 配置
  registryUrl: __DOCKER_REGISTRY_URL__
  registryUsername: __DOCKER_REGISTRY_USERNAME__
  registryPassword: __DOCKER_REGISTRY_PASSWORD__

  # 以下一般不用修改
  volumeWorkspace: /data/devops/workspace
  volumeApps: /data/devops/apps/
  volumeInit: /data/init.sh
  volumeSleep: /data/devops/sleep.sh
  volumeLogs: /data/devops/logs
  volumeCodecc: /data/devops/codecc/
  volumeProjectShare: /data/devops/share
  volumeMavenRepo: /root/.m2/repository
  volumeNpmPrefix: /root/Downloads/npm/prefix
  volumeNpmCache: /root/Downloads/npm/cache
  volumeNpmRc: /root/.npmrc
  volumeCcache: /root/.ccache
  volumeGradleCache: /root/.gradle/caches
  hostPathLinkDir: /tmp/bkci
  hostPathHosts: /etc/hosts

  # docker 母机上的配置，workspace用于存放构建的工作空间，可以以挂载的方式提供
  hostPathWorkspace: __INSTALL_PATH__/public/__MODULE__/docker/workspace
  hostPathApps: __INSTALL_PATH__/public/__MODULE__/docker/apps/
  hostPathInit: __INSTALL_PATH__/__MODULE__/agent-package/script/init.sh
  hostPathSleep: __INSTALL_PATH__/__MODULE__/agent-package/script/sleep.sh
  hostPathLogs: __INSTALL_PATH__/logs/__MODULE__/docker
  hostPathCodecc: /data/devops/codecc
  hostPathProjectShare: __INSTALL_PATH__/public/__MODULE__/docker/share/project
  hostPathMavenRepo: __INSTALL_PATH__/public/__MODULE__/docker/thirdparty/maven_repo
  hostPathNpmPrefix: __INSTALL_PATH__/public/__MODULE__/docker/thirdparty/npm_prefix
  hostPathNpmCache: __INSTALL_PATH__/public/__MODULE__/docker/thirdparty/npm_cache
  hostPathNpmRc: __INSTALL_PATH__/public/__MODULE__/docker/thirdparty/.npmrc
  hostPathCcache: __INSTALL_PATH__/public/__MODULE__/docker/thirdparty/ccache/
  hostPathGradleCache: __INSTALL_PATH__/public/__MODULE__/docker/thirdparty/gradle_caches
  # 需要共享的项目
  shareProjectCodeWhiteList:
  # docker.jar 存储路径
  dockerAgentPath: __INSTALL_PATH__/__MODULE__/agent-package/worker-agent.jar
  downloadDockerAgentUrl: __HTTP_SCHEMA__://__BKCI_FQDN__:__BKCI_HTTP_PORT__/ms/dispatch/gw/build/docker.jar
  # 定期下载
  downloadAgentCron: 0 0 3 * * ?
  landunEnv: prod
  clearLocalImageCron: 0 0 2 * * ?
  localImageCacheDays: 7