name: Agent CI

on:
  push:
    branches: [ master ]
    paths: 
      - 'src/agent/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'src/agent/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: true
      max-parallel: 3
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.12
      - uses: actions/checkout@v2
      - run: ./build_linux.sh
        working-directory: src/agent/
        if: matrix.os == 'ubuntu-latest'
      - run: ./build_macos.sh
        working-directory: src/agent/
        if: matrix.os == 'macos-latest'
      - run: build_windows.bat
        shell: cmd
        working-directory: src/agent/
        if: matrix.os == 'windows-latest'
      - uses: actions/upload-artifact@v1
        with:
          name: agent
          path: src/agent/bin/